##data ingestion confi guration


artifacts_root: artifacts


data_ingestion:
  root_dir:artifacts/data_ingestion
  source_URL:https://github.com/Sanoj12/sample_data/blob/main/winequality-red.zip
  local_data_file:artifacts/data_ingestion/data.zip
  unzip_dir:artifacts/data_ingestion
    



##data vaildatiom


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  


######DATA TRANSFORMATION


data_transformation:
  root_dir: artifacts/data_transformation
  data_path : artifacts/data_ingestion/winequality-red.csv
