##data ingestion confi guration


artifacts_root: artifacts


data_ingestion:
  root_dir:artifacts/data_ingestion
  source_URL:https://github.com/Sanoj12/sample_data/blob/main/winequality-red.zip
  local_data_file:artifacts/data_ingestion/data.zip
  unzip_dir:artifacts/data_ingestion
    



##data vaildatiom


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  


######DATA TRANSFORMATION


data_transformation:
  root_dir: artifacts/data_transformation
  data_path : artifacts/data_ingestion/winequality-red.csv



########MODEL TRAINER######################3

model_trainer:
     root_dir: artifacts/model_trainer
     train_data_path: artifacts/data_transformation/train.csv
     test_data_path: artifacts/data_transformation/test.csv
     model_name : model.joblib




#########################MODEL EVALUATION ###########################


model_evaluation:
  root_dir : artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path : artifacts/model_trainer/model.joblib
  metrics_file_name : artifacts/model_evaluation/metrics.json